
# Google Cloud Platform
# https://console.cloud.google.com/
#   APIとサービス > 認証情報

default: &defaults
  # http://localhost:4000/.well-known/openid-configuration
  # 末尾に "/" は付けない
  issuer: http://localhost:4000

development: 
  <<: *defaults
  # Connect Op Sample 側で発行
  client_id: 5e8cca22e24630aa47e201c987980028
  client_secret: c88f2783e0d4a73d0db105c56144a555023998e3d0d0f3f3e6675552c2f23707
  redirect_uri: http://localhost:3030/auth/connect_op_sample_implicit/callback

test:
  <<: *defaults

production:
  <<: *defaults
  redirect_uri: https://connect-op.herokuapp.com/connect/google
